from fpdf import FPDF
import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(5, 150, 105) # Syngenta Green
        self.cell(0, 10, 'AgriAttribute AI - Syngenta ROI Report', border=False, align='C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by HACK CORE 2026 (Team 15) - Page {self.page_no()}', 0, 0, 'C')

def clean_pdf_text(text):
    """Sanitizes text to ensure safe PDF cell rendering without latin-1 encoding errors."""
    if text is None:
        return ""
    s = str(text)
    replacements = {
        "क्विंटल/एकड़": "q/acre", "क्विंटल/एकर": "q/acre", "క్వింటాల్/ఎకరం": "q/acre",
        "क्विंटल": "q", "₹": "Rs. ", "•": "-", "–": "-", "—": "-",
        "“": '"', "”": '"', "’": "'", "‘": "'"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode('latin-1', 'replace').decode('latin-1')

def generate_roi_pdf(farm_info, roi_data, forecast_data):
    """
    Generates a PDF byte string containing the Farm info, ROI metrics, and 10-day forecast table.
    """
    pdf = PDF()
    pdf.add_page()
    
    # Section 1: Farm Details
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Farm Profile & Biological Input', ln=True)
    
    pdf.set_font('helvetica', '', 11)
    for key, val in farm_info.items():
        pdf.cell(60, 8, clean_pdf_text(key) + ":", border=0)
        pdf.cell(0, 8, clean_pdf_text(val), border=0, ln=True)
    pdf.ln(5)
    
    # Section 2: ROI Analysis
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Yield Attribution & Financial Impact (Per Acre)', ln=True)
    
    pdf.set_font('helvetica', '', 11)
    for key, val in roi_data.items():
        if "Boost" in key or "Profit" in key or "ROI" in key or "+" in str(val):
            pdf.set_text_color(5, 150, 105) # Green highlight
            pdf.set_font('helvetica', 'B', 11)
        else:
            pdf.set_text_color(15, 23, 42)
            pdf.set_font('helvetica', '', 11)
            
        pdf.cell(60, 8, clean_pdf_text(key) + ":", border=0)
        pdf.cell(0, 8, clean_pdf_text(val), border=0, ln=True)
    
    pdf.ln(10)
    pdf.set_text_color(15, 23, 42)
    
    # Section 3: Weather Forecast
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, '5-Day Agro-Meteorological Forecast', ln=True)
    
    # Table Header
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_fill_color(241, 245, 249)
    col_widths = [30, 45, 40, 35, 35]
    headers = ["Date", "Condition", "Temp (Max/Min)", "Humidity", "Wind"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 10, h, border=1, align='C', fill=True)
    pdf.ln()
    
    # Table Rows (up to 5 days)
    pdf.set_font('helvetica', '', 10)
    for day in (forecast_data or [])[:5]:
        if isinstance(day, dict):
            date_str = str(day.get('date', 'Day'))
            cond_text = str(day.get('condition', day.get('desc', 'Clear')))
            temp_max = day.get('temp_max', 30)
            temp_min = day.get('temp_min', 20)
            hum_text = str(day.get('humidity_pct', day.get('humidity', 60)))
            wind_text = str(day.get('wind_kmh', day.get('wind', 10)))
        else:
            date_str = str(day)
            cond_text = "Forecast"
            temp_max, temp_min = 30, 20
            hum_text = "60"
            wind_text = "10"
            
        pdf.cell(col_widths[0], 10, clean_pdf_text(date_str[:10]), border=1, align='C')
        pdf.cell(col_widths[1], 10, clean_pdf_text(cond_text[:15]), border=1, align='C')
        pdf.cell(col_widths[2], 10, f"{temp_max}/{temp_min} C", border=1, align='C')
        pdf.cell(col_widths[3], 10, f"{hum_text}%", border=1, align='C')
        pdf.cell(col_widths[4], 10, f"{wind_text} km/h", border=1, align='C')
        pdf.ln()
        
    pdf.ln(8)
    pdf.set_font('helvetica', 'I', 8)
    pdf.set_text_color(100, 116, 139)
    disclaimer_text = clean_pdf_text(
        "Agronomic & Model Disclaimer: Yield attributions, financial ROI estimates, and weather projections are computed via calibrated machine learning models and official Agmarknet/Soil Health benchmarks. Field responses may vary based on soil microbiology and microclimates. Generated: " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    pdf.multi_cell(0, 4, disclaimer_text)
        
    return pdf.output()
